### ISSUE TITLE
fix for shadowland herb and ore nodes

### ISSUE THREAD

**Issue by ffdevill** [holydeew/KyrianCORE-OpenSource#2]
this will fix the issue of shadowland herb and ore nodes not giving loot added all appropriate loot  as well as amounts and % drop chance  i modified as little as possible  also tested it on a sandbox and it works as intended 

[shadow mining herb.zip](https://github.com/holydeew/KyrianCORE-OpenSource/files/6642732/shadow.mining.herb.zip)

**Comment by subsix-wow** [comment]
Thanks implemented in commit 4ab6f3c
